spring.h2.console.enabled: true

spring:
  profiles:
    location: local
  datasource:
    username: postgres
    password: 1234
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  jwt:
    secret: govlepel@$&
  redis:
    host: localhost
    password: 1234
    port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: pickaboookk@gmail.com
    password: vlzkqnr1!
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  batch:
    job:
      enabled: false