spring.h2.console.enabled: true

spring:
  datasource:
    username: pkqrvmklmegoet
    password: fed34d67388415cb9b23f0a6ea559a44ab07f473d57ce4f9e9460dcf494923bc
    url: jdbc:postgresql://ec2-34-200-119-220.compute-1.amazonaws.com:5432/d93bgiug8lictj
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create