spring.h2.console.enabled: true

spring:
  profiles:
    location: dev
  datasource:
    username: mcyhfhugcuzbdw
    password: 7eb2f7725c501ec3bb9f853df38c0882aca6f5a9062387f6dc2f7c80fa607400
    url: jdbc:postgresql://ec2-18-209-169-66.compute-1.amazonaws.com:5432/d1ngm032j3spr8
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  jwt:
    secret: govlepel@$&
  redis:
    host: spinyfin.redistogo.com
    password: 6dfca28fd1ec503d1030116c2693e696
    port: 10783