spring.h2.console.enabled: true

spring:
  profiles:
    location: prod
  datasource:
    username: wrlcjkkjkofftn
    password: ENC(AUKewXl2THxjTkHsuvs2Ic7bg05FSwOGPfaBWo+VnzrIigi4lmWHl4sBMTdvuHpgzq/HWF+OJxqaPdNpAlfeAbWHNOggCCTqD1Zh2jMmu+s=)
    url: jdbc:postgresql://ec2-54-224-120-186.compute-1.amazonaws.com:5432/d14uvkjkdvu607
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  jwt:
    secret: govlepel@$&
  redis:
    host: scat.redistogo.com
    password: ENC(FnuS29hOJ28uE/g2URiaWmBXZeLdZ1lHBHVDyWE3lrb5JJi2+Xt2fePGa1dYuo6B)
    port: 10273
  mail:
    host: smtp.gmail.com
    port: 587
    username: pickaboookk@gmail.com
    password: ENC(YOtGsjYD29WuFvceCEdYsF1vnE8ukcIr)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true