spring.h2.console.enabled: true

spring:
  profiles:
    location: dev
  datasource:
    username: mcyhfhugcuzbdw
    password: ENC(8vEUlgFRXFUri1GZaVKURieTjBzSLjLmvr3AUn8uklAKUmdckazCLO5snqboh9hagOdcXHdcfp7nRQG9XVY793mp5EZFUUh+aY3XvSFVw/8=)
    url: jdbc:postgresql://ec2-18-209-169-66.compute-1.amazonaws.com:5432/d1ngm032j3spr8
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  jwt:
    secret: govlepel@$&
  redis:
    host: spinyfin.redistogo.com
    password: ENC(LXDVS0RrD84UudCzVW+OyPQXDq+HtnsGvBA+qGlYpmvTjOt5Ev71Ote4te7EBpbx)
    port: 10783
  mail:
    host: smtp.gmail.com
    port: 587
    username: peekabookwork@gmail.com
    password: ENC(Y8MDELigEfxCfEaTFiE3TXML+HtpWpn26VvCPQ50pKI=)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true